# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# cargo publish --allow-dirty --registry crates-io -p liberty-db
[workspace]
members = ["macros", "tests", "examples/*"]

[workspace.package]
version = "0.6.2"
license = "MIT"
edition = "2021"
authors = ["Junzhuo <zhou@junzhuo.site>"]
keywords = [
    "eda",
    "liberty",
    "database",
    "parser",
]
readme = "README.md"
repository = "https://github.com/zao111222333/liberty-db/"
documentation = "https://docs.rs/liberty-db"
categories = ["development-tools"]

[package]
name = "liberty-db"
description = "`liberty` data structre"
include = ["/src", "/tests", "/examples", "/docs/header.html", "README.md"]
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true
categories.workspace = true


# Enable katex in documentation
# RUSTDOCFLAGS="--html-in-header docs/header.html" cargo doc --no-deps --open
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "docs/header.html" ]

[features]
default = []

[dependencies]
# liberty-macros = "0.6.2"
liberty-macros = { path = "macros" }
log = { version = "0.4", features = ["std", "serde"] }
serde = { version = "1.0", features = ["derive"] }
ordered-float = { version = "4.0", features = ["serde"] }
nom = "7.1"
thiserror = "1.0"
lazy_static = "1.4.0"
strum = "0.24"
strum_macros = "0.24"
enum_dispatch = "0.3.11"
derivative = "2.2.0"
prettytable-rs = "^0.10"
itertools = "0.10.5"
ryu = "1.0"
itoa = "1.0"
uom = { version = "0.36.0", default-features = false, features = ["f64", "si", "std", "serde"] }
# biodivine-lib-bdd = { path = "../../biodivine-lib-bdd", features = ["serde"] }
biodivine-lib-bdd = { version = "0.5.19", features = ["serde"] }
mut_set = "0.4.0"
# mut_set = {path = "../mut_set"}
duplicate = "1.0.0"
arcstr = { version = "1.2.0", features = ["serde"] }
num-traits = "0.2.19"
# mexprp = "0.3.1"

[build-dependencies]

[dev-dependencies]
walkdir = "2"
criterion = { version = "0.5", features = ["html_reports"] }
similar = { version = "2.6.0", features = ["inline"]}
console = "0.15.8"
libertyparse = "0.3.0"
liberty-io = "0.0.4"

[[bench]]
name = "benchmark"
harness = false

# anyhow = "1.0.80"

# [profile.dev.build-override]
# opt-level = 3
# codegen-units = 256
# debug = false # when possible