# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# cargo publish --allow-dirty --registry crates-io -p liberty-db
[workspace]
members = ["macros", "tests"]

[workspace.package]
version = "0.4.7"
license = "MIT"
edition = "2021"
authors = ["Junzhuo <zhou@junzhuo.site>"]
keywords = [
    "eda", 
    "liberty",
    "database",
    "parser",
]
readme = "README.md"
repository = "https://github.com/zao111222333/liberty-db/"
documentation = "https://docs.rs/liberty-db"


[package]
name = "liberty-db"
description = "`liberty` data structre"
include = ["/src", "/tests", "/docs/header.html", "/build.rs", "README.md"]
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true

# Enable katex in documentation
# RUSTDOCFLAGS="--html-in-header docs/header.html" cargo doc --no-deps --open
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "docs/header.html" ]

[features]
default = []

[dependencies]
# liberty-macros = "0.4.4"
liberty-macros = { path = "macros" }
log = { version = "0.4", features = ["std", "serde"] }
ordered-float = { version = "4.0", default-features = false }
nom = "7.1"
thiserror = "1.0"
lazy_static = "1.4.0"
strum = "0.24"
strum_macros = "0.24"
enum_dispatch = "0.3.11"
derivative = "2.2.0"
prettytable-rs = "^0.10"
itertools = "0.10.5"
ryu = "1.0"
itoa = "1.0"
uom = { version = "0.36.0", default-features = false, features = ["f64","si", "std","serde"] }
biodivine-lib-bdd = "0.5"
# biodivine-lib-bdd = {path = "../../biodivine-lib-bdd"}
mut_set = "0.3.4"
mut_set_derive = "0.3.4"
# mut_set = {path = "../mut_set"}
# mut_set_derive = {path = "../mut_set/derive"}
duplicate = "1.0.0"

[dev-dependencies]
anyhow = "1.0.80"