[package]
name = "liberty-macros"
version = "0.2.2"
edition = "2021"
license = "MIT"
description = "`liberty` macros"
authors = ["Junzhuo <zhou@junzhuo.site>"]
readme = "README.md"
repository = "https://github.com/zao111222333/liberty-db/"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = {version ="1.0",features = ["extra-traits"]}
quote = "1.0"