name: Compare Branches

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.84.0"

jobs:
  compare-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Check out PR (head)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          path: pr_head
      - name: Check out Base
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.event.pull_request.base.repo.full_name }}
          path: base_branch
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Build commit URLs
        id: buildurl
        run: |
          echo "HEAD_REPO_URL=${{ github.event.pull_request.head.repo.html_url }}/tree/${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          echo "BASE_REPO_URL=${{ github.event.pull_request.base.repo.html_url }}/tree/${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
  
      - name: Debug print
        run: |
          echo "HEAD commit URL: ${{ steps.buildurl.outputs.HEAD_REPO_URL }}"
          echo "BASE commit URL: ${{ steps.buildurl.outputs.BASE_REPO_URL }}"
      - name: Run compare command
        run: |
          cd pr_head
          .github/workflows/compare.sh "${{ steps.buildurl.outputs.BASE_REPO_URL }}" "${{ steps.buildurl.outputs.HEAD_REPO_URL }}"

      - name: Show debug
        run: |
          ls -l pr_head
          cat pr_head/target/criterion/index.html || true

      - name: Post report as PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const reportBody = fs.readFileSync('base_branch/target/criterion/index.html', 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: reportBody
            })