name: Nightly

on:
  schedule:
    - cron: '10 11 * * *'  # 9:10@UTC, 1:10@LA

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      DATE: ${{ steps.date.outputs.DATE }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Date
        id: date
        run: echo "DATE=$(date '+%Y%m%d' -d '-1 day')" >> $GITHUB_OUTPUT
  package:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - name: Package
        run: .github/workflows/package.sh ${{ needs.prepare.outputs.DATE }}
      - name: Archive package
        uses: actions/cache@v4
        with:
          key: package-${{ needs.prepare.outputs.DATE }}
          path: target/package